Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Going for a direct connect...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Going for a direct connect...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Going for a direct connect...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Going for a direct connect...
Checking network connection...
Network is connected. Running post_wifi.sh and RaspiClient.py...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Going for a direct connect...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Going for a direct connect...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Going for a direct connect...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Going for a direct connect...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Going for a direct connect...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Going for a direct connect...
Checking network connection...
Network is connected. Running post_wifi.sh and RaspiClient.py...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Going for a direct connect...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Going for a direct connect...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Going for a direct connect...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Going for a direct connect...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Checking network connection...
Network is connected. Running post_wifi.sh and RaspiClient.py...
Checking network connection...
Network is connected. Running post_wifi.sh and RaspiClient.py...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Going for a direct connect...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
RaspiClient.py encountered an error. Retrying in 5 seconds...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Going for a direct connect...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Going for a direct connect...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Going for a direct connect...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Going for a direct connect...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Going for a direct connect...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Going for a direct connect...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Going for a direct connect...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Going for a direct connect...
Checking network connection...
Network is not connected. Running pre_robot.sh, post_robot.sh, and app.py...
Going for a direct connect...
